services:
  - type: web
    name: fresh-life-style
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PRINTFUL_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
